CREATE TABLE categories
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category VARCHAR(255),
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE goods
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    category_id BIGINT,
    price       DECIMAL,
    quantity    BIGINT,
    CONSTRAINT pk_goods PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    surname  VARCHAR(255),
    position VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE goods
    ADD CONSTRAINT FK_GOODS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);